import LocalizedStrings from 'react-localization';

const Strings = new LocalizedStrings({
    en: {
        appName: "TypeDown",
        login: "Login",
        logOut: "Logout",
        username: "Username",
        password: "Password",
        createAccount: "Create an account",
        loginError: "Wrong username or password.",
        notRegistered: "Not registered yet?",
        email: "Email address",
        create: "Create",
        registerSuccess: "Account successfuly created!",
        alreadyRegistered: "Already a member?",
        createDocument: "Create a document",
        register: "Register",
        newDocument: "New document",
        save: "Save",
        clear: "Clear",
        cancel: "Cancel",
        clearDocumentConfirmation: "Are you sure you want to clear this document?",
        title: "Title",
        required: "Required",
        publishedBy: "Published by",
        pageNotFound: "Page not found...",
        profile: "Profile",
        myDocuments: "My documents",
        tags: "Tags, comma separated"
    },
    fr: {
        appName: "TypeDown",
        login: "Se connecter",
        logOut: "Se déconnecter",
        username: "Pseudonyme",
        password: "Mot de passe",
        createAccount: "Créer un compte",
        loginError: "Identifiant ou mot de passe incorrect.",
        notRegistered: "Pas encore inscrit?",
        email: "Adresse email",
        create: "Créer",
        registerSuccess: "Compte enregistré avec succès!",
        alreadyRegistered: "Déjà inscrit?",
        createDocument: "Créer un document",
        register: "Créer un compte",
        newDocument: "Nouveau document",
        save: "Sauvegarder",
        clear: "Effacer",
        cancel: "Annuler",
        clearDocumentConfirmation: "Êtes-vous sûr de vouloir effacer ce document?",
        title: "Titre",
        required: "Requis",
        publishedBy: "Publié par",
        pageNotFound: "Page non trouvée...",
        profile: "Profil",
        myDocuments: "Mes documents",
        tags: "Tags, séparés par une virgule"
    }
});

export default Strings;